version: '3'

services:
  zabbix-web:
    container_name: zabbix-web
    image: zabbix/zabbix-web-nginx-mysql:6.0.16-centos
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DB_SERVER_HOST=zabbix-mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=zabbix123
      - ZBX_SERVER_HOST=zabbix-server
    ports:
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime
      - ${ServerDataPath:-/data}/zabbix/fonts/DejaVuSans.ttf:/usr/share/zabbix/assets/fonts/DejaVuSans.ttf
      - ${ServerDataPath:-/data}/zabbix/share:/data/zabbix/share
    networks:
      - zbx_net
    depends_on:
      - zabbix-server
      - zabbix-mysql
  zabbix-mysql:
    container_name: zabbix-mysql
    image: mysql:8.0.33
    restart: always
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=zabbix123
    command:
      - mysqld
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      - --max_connections=1000
    volumes:
      - /etc/localtime:/etc/localtime
      - ${ServerDataPath:-/data}/zabbix/db:/var/lib/mysql
      - ${ServerDataPath:-/data}/zabbix/share:/data/zabbix/share
    networks:
      - zbx_net
  zabbix-gateway:
    container_name: zabbix-gateway
    image: zabbix/zabbix-java-gateway:6.0.16-centos
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime
      - ${ServerDataPath:-/data}/zabbix/share:/data/zabbix/share
    networks:
      - zbx_net
  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:6.0.16-centos
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DB_SERVER_HOST=zabbix-mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=zabbix123
      - ZBX_JAVAGATEWAY=zabbix-gateway
      - ZBX_JAVAGATEWAY_ENABLE=true
      - ZBX_JAVAGATEWAYPORT=10052
      - ZBX_DEBUGLEVEL=2
      - ZBX_MAXHOUSEKEEPERDELETE=5000
      - ZBX_STARTPOLLERS=10
      - ZBX_STARTTRAPPERS=200
      - ZBX_CACHESIZE=2G
      - ZBX_HISTORYCACHESIZE=512M
      - ZBX_TRENDCACHESIZE=256M
      - ZBX_VALUECACHESIZE=1G
      - ZBX_LOGSLOWQUERIES=3000
    ports:
      - 10051:10051
    volumes:
      - ${ServerDataPath:-/data}/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
      - /etc/localtime:/etc/localtime
      - ${ServerDataPath:-/data}/zabbix/share:/data/zabbix/share
    depends_on:
      - zabbix-mysql
    networks:
      - zbx_net
  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent:6.0.16-centos
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 10050:10050
    environment:
      - ZBX_HOSTNAME=zabbix-server
      - ZBX_SERVER_HOST=zabbix-server
      - ZBX_SERVER_PORT=10051
    networks:
      - zbx_net
  grafana:
    container_name: grafana
    image: grafana/grafana:9.5.1
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 3000:3000
    user: '0'
    volumes:
      - /etc/localtime:/etc/localtime
      - ${ServerDataPath:-/data}/grafana/data:/var/lib/grafana
      - ${ServerDataPath:-/data}/grafana/plugins:/var/lib/grafana/plugins
      - ${ServerDataPath:-/data}/grafana/datasources:/etc/grafana/provisioning/datasources      
      - ${ServerDataPath:-/data}/zabbix/share:/data/zabbix/share
    networks:
      - zbx_net
networks:
  zbx_net:
    driver: bridge
