version: '3'
services:
  mysql8:
    platform: linux/amd64
    image: mysql:8.0.33
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: '234567'
    ports:
      - '3386:3306'
    expose:
      - '3386'
    volumes:
      - /data/mysql:/var/lib/mysql
